SELECT DISTINCT CITY 
FROM STATION 
WHERE RIGHT(CITY, 1) IN ('a', 'e', 'i', 'o', 'u');

OR

SELECT DISTINCT CITY 
FROM STATION 
WHERE SUBSTRING(CITY, LEN(CITY), 1) IN ('a', 'e', 'i', 'o', 'u');